version: "3.8"

services:

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped

    networks:
      - guacnet


  postgres:
    image: postgres:16-alpine
    container_name: guacamole-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: guacdb

    volumes:
      - guacamole_db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

    networks:
      - guacnet


  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    restart: unless-stopped

    depends_on:
      - guacd
      - postgres

    ports:
      - "8080:8080"

    environment:

      GUACD_HOSTNAME: guacd

      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole
      POSTGRESQL_PASSWORD: guacdb

    networks:

      guacnet:

      ipvlan_net:
        ipv4_address: 192.168.1.223


volumes:

  guacamole_db:


networks:

  guacnet:
    driver: bridge


  ipvlan_net:
    external: true
